### ISSUE TITLE
Styles are missing

### ISSUE THREAD

**Issue by JohnNiang** [bytealan/halo-theme-oranges#1]
Please see the screenshot below:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/16865714/219589317-9a2e4799-fe31-4d29-945e-223d4214baa9.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/16865714/219589434-31b88118-b623-41c0-8d1e-23d3b38e4de3.png">

**Comment by allendevx** [comment]
zip安装的吗？

**Comment by WuWenL0** [comment]
见[RD](https://github.com/WuWenL0/halo-theme-oranges/blob/main/README.md#%E5%BC%80%E5%8F%91)

**Comment by allendevx** [comment]
我这重装试了一下，没什么问题....

**Comment by JohnNiang** [comment]
我是从 https://github.com/WuWenL0/halo-theme-oranges/archive/refs/heads/main.zip 下载并安装的主题。样式问题仍旧存在。

**Comment by JohnNiang** [comment]
刚刚看了一下 README.md，发现得从 Release 中下载 ZIP 包。目前可以正常使用了，感谢！

<img width="985" alt="image" src="https://user-images.githubusercontent.com/16865714/219613341-768a087a-6c60-4fe3-882b-db2f5b62d5e9.png">
