### ISSUE TITLE
无法添加(显示)网站备案信息

### ISSUE THREAD

**Issue by MagiDrag0n** [bytealan/halo-theme-oranges#2]
开发者你好，

在oranges主题当中没有页脚网站备案信息展示的选项，故尝试在halo主题的设置下添加页脚代码形如下：

`<a href="http://beian.miit.gov.cn/" style="color:#f72b07" target="_blank"> X ICP备XXX号-1 </a>`

保存后查看发现没有生效，同时检查换用主题的情况下可以显示。

希望得到你的回复，谢谢！

**Comment by allendevx** [comment]
Sorry, 我的锅 疏忽了,马上改

**Comment by allendevx** [comment]
1.0.1已经添加了
请在[releases](https://github.com/WuWenL0/halo-theme-oranges/releases)下载最新主题安装包

升级方式1：
2. 进入主题管理页面，点击升级按钮，传入最新主题zip包
3. 升级后需要重载主题配置或在主题配置页面的备案信息选项卡中点一下保存按钮，不然会报错

升级方式2：
把现有主题卸载后，重新安装也是可以的

**Comment by MagiDrag0n** [comment]
开发者你好，

在升级主题之后，显示正常了。

谢谢，敬颂时祺！
