### ISSUE TITLE
博客归档显示时间错误

### ISSUE THREAD

**Issue by MagiDrag0n** [bytealan/halo-theme-oranges#3]
开发者好，

在您博客当中的归档页面，时间显示错误如下：
![Screensho](https://user-images.githubusercontent.com/41734083/220072734-c3f47c0b-7482-49d0-91a1-147daad39e25.png)

我个人博客部署后发布文章的操作流程是：将以前博客的markdown内容复制到Halo后台中发布，再调整了文章时间。于是也遇到了这个情况。不额外调整发布时间发布新文章则没有这个问题。

麻烦您了，望回复，谢谢！

**Comment by allendevx** [comment]
您好

感谢您使用这个主题和提交Issue

[releases](https://github.com/WuWenL0/halo-theme-oranges/releases)已经修复了该问题

直接进行升级 操作即可

**Comment by allendevx** [comment]
使用上给您带来不便了，万分抱歉

**Comment by MagiDrag0n** [comment]
开发者你好，

新版的主题解决了显示问题。

谢谢！
