### ISSUE TITLE
打开文章显示的发表时间不是后台配置的文章发表时间

### ISSUE THREAD

**Issue by 1518830942** [bytealan/halo-theme-oranges#4]
![1677338837095](https://user-images.githubusercontent.com/40021838/221365536-8b95eb8d-7f42-47e6-85fb-8cdcce2faef4.jpg)
![1677338891796](https://user-images.githubusercontent.com/40021838/221365541-f0755dba-d2f3-4d52-b1d4-eb73d2881212.jpg)

**Comment by allendevx** [comment]
您好，
这个位置显示的是文章的最后更新时间并不是创建时间。

**Comment by 1518830942** [comment]
> 

好的，了解了，谢谢作者
