### ISSUE TITLE
请教一个问题，halo博客怎么支持atom订阅

### ISSUE THREAD

**Issue by SimonGino** [bytealan/halo-theme-oranges#7]
类似  https://www.wuqiongda.store/atom.xml   这样的链接。
holo最新版本可以实现支持atom订阅吗，因为我看他有content标签（可以完全展示文章内容），而现在我用的只有description标签，不可以完全展示我的内容。

**Comment by allendevx** [comment]
不好意思这个我也不太清楚，目前官方只提供了[RSS](https://github.com/halo-sigs/plugin-feed)的插件，您可以仿照该版本，自定义一个插件

**Comment by SimonGino** [comment]
已经解决，拉了代码看了下，原来有个枚举，可以配置全文或者摘要的，傻呗了 : (
